#!/bin/csh -f

if ($#argv > 0 ) then
	set cardname = $1
else
	set cardname = pythia_direct_photoproduction
endif

echo "Running Pythia inside Amadeus."
echo "Trying to use control cards from ${cardname}.cards"
echo "Output goes to ${cardname}.log"

rm -f fort.7
rm -f fort.11
rm -f fort.9
rm -f fort.10

ln -s particle.data   fort.9
cp ${cardname}.cards  fort.7
ln -s amadeus.rndm    fort.10

set amadir = /afs/desy.de/group/zeus.zsmsm/ZEUSSysSoft/Released/Support/Monte_Carlo/Generators/amadeus/v2010a/exe/i586-sl5-linux

# Choose Pythia Pythia 6.416 or Pythia 6.221

$amadir/amadeus_pythia6416.exe >& ${cardname}.log 
#$amadir/amadeus_pythia6221.exe >& ${cardname}.log &

